language: rust
cache: cargo
sudo: false


# rust:
#   - stable
#   - beta
#   - nightly

# env:
#   global:
#     - CRATE_NAME=mdbook-mosta

  # Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
cache:
  directories:
    - /home/travis/.cargo

git:
  depth: false

matrix:
  fast_finish: true
  include:
    - name: Tests
      env: RUST_BACKTRACE=1
      rust: nightly
      script:
      - cargo test --locked
      # - rustup component add rustfmt-preview
      # - cargo fmt --version
      # - cargo fmt --all -- --check
    # Build and deploy the mdbook guide.
    - name: Book
      rust: nightly
      before_script:
      # - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      - (test -x $HOME/.cargo/bin/mdbook-mosta || cargo install --git https://github.com/smolkov/mdbook-mosta.git)
      script:
      - (cd docs && $HOME/.cargo/bin/mdbook-mosta build)
      deploy:
        provider: pages
        skip-cleanup: true
        # github-token: $GITHUB_TOKEN
        local-dir: docs/book
        keep-history: false
        on:
          branch: master
