[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "no-std",
]
description = "Board support crate for the STM32 Nucleo-F042K6 microcontroller board"
documentation = "https://docs.rs/nucleo-f042k6"
keywords = [
    "arm",
    "cortex-m",
    "template",
]
license = "0BSD"
name = "nucleo-f042k6"
repository = "https://github.com/therealprof/nucleo-f042k6"
version = "0.4.0"

[dependencies]
cortex-m = "0.5.7"
cortex-m-rt = "0.6.4"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"

[dependencies.stm32f042-hal]
features = ["rt"]
version = "0.6.0"

[dev-dependencies]
ssd1306 = "0.2.0"
nb = "0.1.1"
panic-abort = "0.3.1"
ina260 = "0.2.2"
sevensegment = "0.1.0"

[dev-dependencies.shared-bus]
features = ["cortexm"]
optional = false
version = "0.1.2"

[features]
default = ["rt"]
rt = []

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"
